config/routes.rb
require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  resources :sms_cancellations, only: :create

  namespace :mail_gun do
    resources :drops, only: :create
  end

  resources :my_appointments, only: :index

  resources :users, only: :update

  resources :appointments, only: %i(index edit update) do
    resource :cancel, only: :create
    resource :process, only: :create
    resources :changes, only: :index

    resource :reschedule, only: %w(create show)
  end

  resources :booking_requests, only: %i(index update) do
    resources :activities, only: %i(index create)

    resources :appointments, only: %i(new create)

    resource :postal_address, only: %i(edit update)

    resource :confirmation, only: :create
    resource :video_confirmation, only: :create

    resource :consent, only: %i(update show)
  end

  resources :schedules, only: :index

  resources :locations, only: :index

  resources :realtime_bookable_slots, only: [] do
    post :bsl, on: :member, to: 'bsl#create'
    delete :bsl, on: :member, to: 'bsl#destroy'
  end

  scope '/locations/:location_id' do
    resources :realtime_bookable_slots, only: %w(index create destroy) do
      delete 'future', on: :collection
    end
    resources :realtime_bookable_slot_copies, only: %w(new create) do
      post 'preview', on: :collection
    end
    resources :realtime_bookable_slot_lists, only: :index
    resources :realtime_appointments, only: :index
    resources :guiders, only: :index
  end

  namespace :agent, path: '/locations/:location_id' do
    resources :booking_requests, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :agent, path: '/agents' do
    resources :booking_requests, only: :index, as: :search
    resources :appointments, only: %i(edit update) do
      resource :reschedule, only: %w(create show)
    end
  end

  namespace :booking_manager, path: '/locations/:location_id' do
    resources :appointments, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :admin, path: '/admin' do
    resource :search, only: :show
  end

  root 'home#index'

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      resources :searches, only: :index
      resources :booking_requests, only: :create do
        patch :batch_reassign, on: :collection
      end
    end

    namespace :v2 do
      get '/locations/:location_id/bookable_slots', to: 'bookable_slots#index', as: :bookable_slots
    end
  end

  mount Sidekiq::Web, at: '/sidekiq', constraints: AuthenticatedUser.new
end
# rubocop:enable Metrics/BlockLength

app/controllers/realtime_bookable_slot_lists_controller.rb
class RealtimeBookableSlotListsController < ApplicationController
  def index
    @search = BookableSlotSearch.new(search_params)
    @slots  = @search.results
  end

  private

  def search_params
    params
      .fetch(:search, {})
      .permit(:date, :guider, :per_page)
      .merge(
        page: params[:page],
        location: location
      )
  end

  def location
    @location ||= booking_location.location_for(params[:location_id])
  end
  helper_method :location

  def guiders
    booking_location
      .guiders
      .reject { |guider| guider.name.start_with?('[INACTIVE]') }
  end
  helper_method :guiders
end

app/views/realtime_bookable_slot_lists/index.html.erb
<% content_for(:page_title, t('service.title', page_title: "Realtime bookable slots for #{location.name}")) %>
<div class="page-header">
 <ol class="breadcrumb">
   <li><a href="<%= root_path %>">Planner</a></li>
   <li><%= link_to 'Schedules', schedules_path %></li>
   <li class="active">Realtime bookable slots for <%= location.name %></li>
 </ol>

 <h1>Realtime bookable slots for <%= location.name %></h1>

<div class="t-search filters">
  <div class="panel panel-default">
    <header class="panel-heading">
      <%= form_for @search, url: realtime_bookable_slot_lists_path(location_id: location.id), as: :search, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <ul class="nav nav-compact nav-pills filters__nav">
          <li class="filters__item">
            <%= f.label :date, 'Date', class: 'filters__label' %><%= f.text_field :date, class: 'js-date-range-picker t-date form-control filters__form-control', readonly: true, data: { module: 'date-range-picker' } %>
          </li>
          <li class="filters__item">
            <%= f.label :guider, class: 'filters__label' %>
            <%= f.collection_select :guider, guiders, :id, :name, { include_blank: 'All Guiders' }, { class: 't-room form-control filters__form-control filters__form-control--room' } %>
          </li>
          <li class="filters__item">
            <%= f.label :per_page, class: 'filters__label' %>
            <%= f.select :per_page, [10, 20, 50, 100], {}, { class: 't-per-page form-control filters__form-control filters__form-control--per-page' } %>
          </li>
          <li class="filters__item">
           <%= f.button class: 't-submit btn btn-default filters__button' do %>
             <span aria-hidden="true" class="glyphicon glyphicon-search"></span> Search
           <% end %>
          </li>
        </ul>
      <% end %>
    </header>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @slots.empty? %>
      <p class="no-content t-notice">No realtime bookable slots for <%= location.name %>.</p>
    <% else %>
      <%= paginate @slots %>

      <table class="table table-bordered centred-table table-striped">
        <caption><span class="sr-only">Realtime bookable slots for <%= location.name %></span></caption>
        <thead>
          <tr class="table-header">
            <th>Start at</th>
            <th>Guider</th>
            <th>Available</th>
            <th>Created</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @slots.each do |slot| %>
            <% slot = LocationAwareEntity.new(entity: slot, booking_location: booking_location) %>
            <tr class="t-slot">
              <td class="t-start-at"><%= slot.start_at.to_s(:govuk_date) %></td>
              <td class="t-guider"><%= slot.guider_name %></td>
              <td class="t-available"><%= slot.appointment_count.zero? ? 'Yes' : 'No' %></td>
              <td class="t-created-at"><%= slot.created_at.in_time_zone('London').to_s(:govuk_date) %></td>
              <td>
                <%= link_to realtime_bookable_slot_path(slot, location_id: location.id), title: 'Delete this slot', class: 'btn btn-danger t-delete', method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                  <span class="sr-only">Delete</span>
                <% end %>
                <% if slot.bsl? %>
                  <%= link_to bsl_realtime_bookable_slot_path(slot), title: 'Revert this slot from BSL/double', class: 'btn btn-danger t-bsl', method: :delete, data: { confirm: 'Are you sure you want to revert this slot from BSL/double?' } do %>
                    <span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span>
                    <span class="sr-only">Revert from BSL</span>
                  <% end %>
                <% else %>
                  <%= link_to bsl_realtime_bookable_slot_path(slot), title: 'Convert this slot to BSL/double', class: 'btn btn-info t-bsl', method: :post, data: { confirm: 'Are you sure you want to convert this slot to BSL/double?' } do %>
                    <span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span>
                    <span class="sr-only">Convert to BSL</span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @slots %>
    <% end %>
  </div>
</div>