config/routes.rb
require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  resources :sms_cancellations, only: :create

  namespace :mail_gun do
    resources :drops, only: :create
  end

  resources :my_appointments, only: :index

  resources :users, only: :update

  resources :appointments, only: %i(index edit update) do
    resource :cancel, only: :create
    resource :process, only: :create
    resources :changes, only: :index

    resource :reschedule, only: %w(create show)
  end

  resources :booking_requests, only: %i(index update) do
    resources :activities, only: %i(index create)

    resources :appointments, only: %i(new create)

    resource :postal_address, only: %i(edit update)

    resource :confirmation, only: :create
    resource :video_confirmation, only: :create

    resource :consent, only: %i(update show)
  end

  resources :schedules, only: :index

  resources :locations, only: :index

  resources :realtime_bookable_slots, only: [] do
    post :bsl, on: :member, to: 'bsl#create'
    delete :bsl, on: :member, to: 'bsl#destroy'
  end

  scope '/locations/:location_id' do
    resources :realtime_bookable_slots, only: %w(index create destroy) do
      delete 'future', on: :collection
    end
    resources :realtime_bookable_slot_copies, only: %w(new create) do
      post 'preview', on: :collection
    end
    resources :realtime_bookable_slot_lists, only: :index
    resources :realtime_appointments, only: :index
    resources :guiders, only: :index
  end

  namespace :agent, path: '/locations/:location_id' do
    resources :booking_requests, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :agent, path: '/agents' do
    resources :booking_requests, only: :index, as: :search
    resources :appointments, only: %i(edit update) do
      resource :reschedule, only: %w(create show)
    end
  end

  namespace :booking_manager, path: '/locations/:location_id' do
    resources :appointments, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :admin, path: '/admin' do
    resource :search, only: :show
  end

  root 'home#index'

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      resources :searches, only: :index
      resources :booking_requests, only: :create do
        patch :batch_reassign, on: :collection
      end
    end

    namespace :v2 do
      get '/locations/:location_id/bookable_slots', to: 'bookable_slots#index', as: :bookable_slots
    end
  end

  mount Sidekiq::Web, at: '/sidekiq', constraints: AuthenticatedUser.new
end
# rubocop:enable Metrics/BlockLength

app/controllers/realtime_bookable_slots_controller.rb
class RealtimeBookableSlotsController < ApplicationController
  before_action :load_schedule
  before_action :load_window

  def index
    @location = booking_location.location_for(params[:location_id])

    respond_to do |format|
      format.html
      format.json { render_realtime_bookable_slots_json }
    end
  end

  def create
    @bookable_slot = @schedule.create_realtime_bookable_slot(
      start_at: Time.zone.parse(params[:start_at]),
      guider_id: params[:guider_id]
    )

    respond_to do |format|
      format.js do
        return head :ok if @bookable_slot.persisted?

        render :errors, layout: false, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @schedule.bookable_slots.realtime.destroy(params[:id])

    respond_to do |format|
      format.js { head :no_content }
      format.html do
        redirect_back fallback_location: realtime_bookable_slot_lists_path(location_id: @schedule.location_id),
                      success: 'The slot was deleted'
      end
    end
  end

  def future
    @schedule
      .bookable_slots
      .realtime
      .where('start_at >= ?', Time.current.beginning_of_day)
      .destroy_all

    redirect_back fallback_location: schedules_path, success: 'The schedule was successfully cleared'
  end

  private

  def load_window
    @window = GracePeriod.new(params[:location_id])
  end

  def load_schedule
    @schedule = Schedule.current(params[:location_id])
  end

  def render_realtime_bookable_slots_json
    render json: @schedule.bookable_slots_in_window(**date_range).realtime.all,
           each_serializer: CalendarBookableSlotSerializer
  end

  def date_range
    {
      starting: params.fetch(:start) { Date.current.beginning_of_day }.to_date,
      ending: params.fetch(:end) { Date.current.end_of_day }.to_date
    }
  end
end

app/views/realtime_bookable_slots/errors.js.erb
alertify.alert(
  '<strong class="text-danger">You cannot create a slot here</strong>',
  '<p><%= raw @bookable_slot.errors.full_messages.map(&:capitalize).join("<br>") %></p>'
);

app/views/realtime_bookable_slots/index.html.erb
<% content_for(:page_title, t('service.title', page_title: "Realtime availability for #{@location.name}")) %>
<div class="page-header">
 <ol class="breadcrumb">
   <li><a href="<%= root_path %>">Planner</a></li>
   <li><%= link_to 'Schedules', schedules_path %></li>
   <li class="active">Realtime availability for <%= @location.name %></li>
 </ol>

 <h1>
   Realtime availability for <%= @location.name %><br>
   <small>Booking window from <%= @window.start.to_s(:govuk_date) %> to <%= @window.end.to_s(:govuk_date) %></small>
 </h1>
</div>

<div class="alert alert-success js-success t-success" role="alert" style="display:none;">
  <span class="glyphicon glyphicon-ok"></span> Slot was modified successfully.
</div>

<div
 id="RealtimeCalendar"
 class="js-calendar realtime-calendar t-calendar"
 data-module="realtime-calendar"
 data-default-date="<%= Time.zone.now.iso8601 %>"
 data-guiders-uri="<%= guiders_path(location_id: @location.id) %>"
 data-slots-uri="<%= realtime_bookable_slots_path(location_id: @location.id) %>"
 data-appointments-uri="<%= realtime_appointments_path(location_id: @location.id) %>"
 data-copy-slots-uri="<%= new_realtime_bookable_slot_copy_path(location_id: @location.id) %>">

 <div class="modal <%= 'fade' unless Rails.env.test? %> js-copy-modal t-copy-modal" tabindex="-1" role="dialog">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
     </div>
   </div>
 </div>
</div>