config/routes.rb
require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  resources :sms_cancellations, only: :create

  namespace :mail_gun do
    resources :drops, only: :create
  end

  resources :my_appointments, only: :index

  resources :users, only: :update

  resources :appointments, only: %i(index edit update) do
    resource :cancel, only: :create
    resource :process, only: :create
    resources :changes, only: :index

    resource :reschedule, only: %w(create show)
  end

  resources :booking_requests, only: %i(index update) do
    resources :activities, only: %i(index create)

    resources :appointments, only: %i(new create)

    resource :postal_address, only: %i(edit update)

    resource :confirmation, only: :create
    resource :video_confirmation, only: :create

    resource :consent, only: %i(update show)
  end

  resources :schedules, only: :index

  resources :locations, only: :index

  resources :realtime_bookable_slots, only: [] do
    post :bsl, on: :member, to: 'bsl#create'
    delete :bsl, on: :member, to: 'bsl#destroy'
  end

  scope '/locations/:location_id' do
    resources :realtime_bookable_slots, only: %w(index create destroy) do
      delete 'future', on: :collection
    end
    resources :realtime_bookable_slot_copies, only: %w(new create) do
      post 'preview', on: :collection
    end
    resources :realtime_bookable_slot_lists, only: :index
    resources :realtime_appointments, only: :index
    resources :guiders, only: :index
  end

  namespace :agent, path: '/locations/:location_id' do
    resources :booking_requests, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :agent, path: '/agents' do
    resources :booking_requests, only: :index, as: :search
    resources :appointments, only: %i(edit update) do
      resource :reschedule, only: %w(create show)
    end
  end

  namespace :booking_manager, path: '/locations/:location_id' do
    resources :appointments, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :admin, path: '/admin' do
    resource :search, only: :show
  end

  root 'home#index'

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      resources :searches, only: :index
      resources :booking_requests, only: :create do
        patch :batch_reassign, on: :collection
      end
    end

    namespace :v2 do
      get '/locations/:location_id/bookable_slots', to: 'bookable_slots#index', as: :bookable_slots
    end
  end

  mount Sidekiq::Web, at: '/sidekiq', constraints: AuthenticatedUser.new
end
# rubocop:enable Metrics/BlockLength

app/controllers/postal_addresses_controller.rb
class PostalAddressesController < ApplicationController
  before_action :fetch_booking_request
  before_action :populate_postal_address

  def edit
  end

  def update
    if @postal_address.update(postal_address_params)
      redirect_to destination_url
    else
      render :edit
    end
  end

  private

  def fetch_booking_request
    @booking_request = current_user.booking_requests.find(params[:booking_request_id])
  end

  def populate_postal_address
    @postal_address = PostalAddressForm.new(@booking_request)
  end

  def postal_address_params
    params
      .fetch(:postal_address, {})
      .permit(
        :address_line_one,
        :address_line_two,
        :address_line_three,
        :town,
        :county,
        :postcode
      )
  end

  def destination_url
    if @booking_request.appointment
      edit_appointment_url(@booking_request.appointment)
    else
      new_booking_request_appointment_url(@booking_request)
    end
  end
end

app/views/postal_addresses/edit.html.erb
<% content_for(:page_title, t('service.title', page_title: "Edit postal address for #{@booking_request.name}")) %>

<div class="page-header">
  <ol class="breadcrumb">
    <li><a href="<%= root_path %>">Planner</a></li>
    <% if @booking_request.appointment %>
      <li><a href="<%= appointments_path %>">Appointments</a></li>
      <li><a href="<%= edit_appointment_path(@booking_request.appointment) %>"><%= @booking_request.name %></a></li>
    <% else %>
      <li><a href="<%= booking_requests_path %>">Booking requests</a></li>
      <li><a href="<%= new_booking_request_appointment_path(@booking_request) %>"><%= @booking_request.name %></a></li>
    <% end %>
    <li class="active">Edit postal address</li>
  </ol>

  <h1>
    Edit postal address for <%= @booking_request.name %><br>
    <small>Booking reference: <%= @booking_request.reference %></small>
  </h1>
</div>

<%= form_for @postal_address, url: booking_request_postal_address_path(@booking_request), as: :postal_address, method: :patch do |f| %>
  <div class="row">
    <div class="col-md-6 l-booking-request-details">
      <% if @postal_address.errors.any? %>
        <div class="alert alert-danger t-errors" role="alert">
          <h3 class="alert__heading h4">There's a problem</h3>
          <ul>
            <% @postal_address.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <h2 class="h3" id="postal-address-heading" data-postcode-api-key="<%= postcode_api_key %>">Confirmation address <small>(required if no email address)</small></h2>
          <div class="form-group">
            <%= f.label :address_line_one do %>
              Building and street <span class="sr-only">line one</span>
            <% end %>
            <%= f.text_field :address_line_one, class: 'form-control t-address-line-one' %>
          </div>
          <div class="form-group">
            <%= f.label :address_line_two, class: 'sr-only' %>
            <%= f.text_field :address_line_two, class: 'form-control t-address-line-two' %>
          </div>
          <div class="form-group">
            <%= f.label :address_line_three, class: 'sr-only' %>
            <%= f.text_field :address_line_three, class: 'form-control t-address-line-three' %>
          </div>
          <div class="form-group">
            <%= f.label :town %>
            <%= f.text_field :town, class: 'form-control t-town' %>
          </div>
          <div class="form-group">
            <%= f.label :county %>
            <%= f.text_field :county, class: 'form-control t-county' %>
          </div>
          <div class="form-group">
            <%= f.label :postcode %>
            <%= f.text_field :postcode, class: 'form-control t-postcode' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= f.button 'Update postal address', class: 'btn btn-primary t-submit' %>
          <% if @booking_request.appointment %>
            <%= link_to 'Cancel', edit_appointment_path(@booking_request.appointment), class: 'btn btn-default t-cancel' %>
          <% else %>
            <%= link_to 'Cancel', new_booking_request_appointment_path(@booking_request), class: 'btn btn-default t-cancel' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script type="text/html" id="postcode-lookup-template">
  <div class="form-group form-inline postcode-lookup" id="postcode-lookup">
    <label for="appointment_summary_lookup" class="sr-only">Postcode or address to search for</label><br>
    <input class="form-control input-md-3 add-right-margin" placeholder="Enter postcode or address" type="text" id="postcode-lookup-input" />
    <button class="btn btn-success btn-sm" onclick="return false" id="postcode-lookup-button">Find UK address</button>
  </div>
  <div class="form-group form-inline" id="postcode-lookup-results-container">
  </div>
</script>