config/routes.rb
require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  resources :sms_cancellations, only: :create

  namespace :mail_gun do
    resources :drops, only: :create
  end

  resources :my_appointments, only: :index

  resources :users, only: :update

  resources :appointments, only: %i(index edit update) do
    resource :cancel, only: :create
    resource :process, only: :create
    resources :changes, only: :index

    resource :reschedule, only: %w(create show)
  end

  resources :booking_requests, only: %i(index update) do
    resources :activities, only: %i(index create)

    resources :appointments, only: %i(new create)

    resource :postal_address, only: %i(edit update)

    resource :confirmation, only: :create
    resource :video_confirmation, only: :create

    resource :consent, only: %i(update show)
  end

  resources :schedules, only: :index

  resources :locations, only: :index

  resources :realtime_bookable_slots, only: [] do
    post :bsl, on: :member, to: 'bsl#create'
    delete :bsl, on: :member, to: 'bsl#destroy'
  end

  scope '/locations/:location_id' do
    resources :realtime_bookable_slots, only: %w(index create destroy) do
      delete 'future', on: :collection
    end
    resources :realtime_bookable_slot_copies, only: %w(new create) do
      post 'preview', on: :collection
    end
    resources :realtime_bookable_slot_lists, only: :index
    resources :realtime_appointments, only: :index
    resources :guiders, only: :index
  end

  namespace :agent, path: '/locations/:location_id' do
    resources :booking_requests, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :agent, path: '/agents' do
    resources :booking_requests, only: :index, as: :search
    resources :appointments, only: %i(edit update) do
      resource :reschedule, only: %w(create show)
    end
  end

  namespace :booking_manager, path: '/locations/:location_id' do
    resources :appointments, only: %i(new create show) do
      post 'preview', on: :collection
    end
  end

  namespace :admin, path: '/admin' do
    resource :search, only: :show
  end

  root 'home#index'

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      resources :searches, only: :index
      resources :booking_requests, only: :create do
        patch :batch_reassign, on: :collection
      end
    end

    namespace :v2 do
      get '/locations/:location_id/bookable_slots', to: 'bookable_slots#index', as: :bookable_slots
    end
  end

  mount Sidekiq::Web, at: '/sidekiq', constraints: AuthenticatedUser.new
end
# rubocop:enable Metrics/BlockLength

app/models/activity.rb
class Activity < ActiveRecord::Base
  POLLING_KEY = 'POLL_INTERVAL_MILLISECONDS'.freeze

  belongs_to :booking_request
  belongs_to :user, optional: true

  scope :since, ->(since) { where('created_at > ?', since) }

  def owner_name
    user ? user.name : 'Someone'
  end

  def to_partial_path
    "activities/#{model_name.singular}"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = booking_request.activities.since(since)

    if @activities.present?
      render partial: @activities
    else
      head :not_modified
    end
  end

  def create
    @activity = MessageActivity.create(message_params)

    respond_to do |format|
      format.js { render @activity }
    end
  end

  protected

  def authorise!
    authorise_user!(
      any_of: [User::BOOKING_MANAGER_PERMISSION, User::AGENT_PERMISSION, User::AGENT_MANAGER_PERMISSION]
    )
  end

  private

  def message_params
    params
      .require(:activity)
      .permit(:message)
      .merge(
        user: current_user,
        booking_request: booking_request
      )
  end

  def since
    timestamp = params[:timestamp].to_i / 1000
    Time.zone.at(timestamp)
  end

  def booking_request
    if current_user.agent? || current_user.agent_manager?
      BookingRequest.find(params[:booking_request_id])
    else
      current_user.booking_requests.find(params[:booking_request_id])
    end
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
  def timestamp(created_at)
    zoned = created_at.in_time_zone('London')

    "#{zoned.to_s(:govuk_date)} (#{time_ago_in_words(zoned)} ago)"
  end
end

app/views/activities/_activation_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= activation_activity.id %>">
  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  <b><%= activation_activity.owner_name %></b> made the booking request <%= activation_activity.message %>
  <span class="activity-feed__date"><%= timestamp(activation_activity.created_at) %></span>
</li>

app/views/activities/_activity_feed.html.erb
<div class="row t-activity-feed">
  <div class="col-md-12 border-bottom">
    <h2 class="h3">Recent activity</h2>

    <div class="activity-feed">
      <div class="well js-message-form">
        <%= form_for booking_request.activities.build, url: booking_request_activities_path(booking_request), remote: true do |f| %>
          <div class="input-group">
            <%= f.text_field :message, placeholder: 'Add an action to keep others in the loop', class: 'form-control js-message t-message' %>
            <span class="input-group-btn">
              <%= f.button class: 'btn btn-info btn-block t-submit-message', data: { disable_with: 'Adding message...' } do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add message
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
      <ul class="activity-feed__list js-poller"
        data-interval="<%= poll_interval_milliseconds %>"
        data-url="<%= booking_request_activities_path(booking_request) %>"><%= render activities.first if activities.present? %></ul>

      <% if activities.count > 1 %>
        <ul class="activity-feed__list t-hidden-activities" id="collapse"><%= render(activities - Array(activities.first)) %></ul>
        <button class="activity-feed__btn btn btn-default t-further-activities hidden" data-target="#collapse" data-toggle="collapse" aria-expanded="false" aria-controls="collapse">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          All activity
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/_appointment_mail_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= appointment_mail_activity.id %>">
  <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
  <strong>The system</strong> sent an email to the customer informing them
  their appointment has been <%= appointment_mail_activity.message %>
  <span class="activity-feed__date"><%= timestamp(appointment_mail_activity.created_at) %></span>
</li>

app/views/activities/_email_third_party_consent_form_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= email_third_party_consent_form_activity.id %>">
  <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
  <strong>The system</strong> sent an email third party <%= link_to 'consent form', booking_request_consent_path(email_third_party_consent_form_activity.booking_request) %>
  <span class="activity-feed__date"><%= timestamp(email_third_party_consent_form_activity.created_at) %></span>
</li>

app/views/activities/_fulfilment_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= fulfilment_activity.id %>">
  <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
  <b><%= fulfilment_activity.owner_name %></b> booked the appointment
  <span class="activity-feed__date"><%= timestamp(fulfilment_activity.created_at) %></span>
</li>

app/views/activities/_message_activity.js.erb
$("<%= j(render partial: @activity, formats: :html) %>").hide().prependTo($('.activity-feed__list:first-of-type')).fadeIn();
$('.js-message').val('');

app/views/activities/_printed_confirmation_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= printed_confirmation_activity.id %>">
  <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
  <b>The system</b> requested a printed confirmation letter
  <span class="activity-feed__date"><%= timestamp(printed_confirmation_activity.created_at) %></span>
</li>

app/views/activities/_printed_third_party_consent_form_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= printed_third_party_consent_form_activity.id %>">
  <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
  <b>The system</b> requested a printed third party consent form letter
  <span class="activity-feed__date"><%= timestamp(printed_third_party_consent_form_activity.created_at) %></span>
</li>

app/views/activities/_processed_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= processed_activity.id %>">
  <span class="glyphicon glyphicon-flag" aria-hidden="true"></span>
  <strong><%= processed_activity.owner_name %></strong> processed the appointment
  <span class="activity-feed__date"><%= timestamp(processed_activity.created_at) %></span>
</li>

app/views/activities/_reassignment_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= reassignment_activity.id %>">
  <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>
  <b>Booking location reassignment: </b>
  <em>the booking was reassigned.</em>
  <span class="activity-feed__date"><%= timestamp(reassignment_activity.created_at) %></span>
</li>

app/views/activities/_sms_cancellation_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= sms_cancellation_activity.id %>">
  <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
  <strong>The customer</strong> cancelled their appointment via SMS
  <span class="activity-feed__date"><%= timestamp(sms_cancellation_activity.created_at) %></span>
</li>

app/views/activities/_sms_reminder_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= sms_reminder_activity.id %>">
  <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
  <strong>The system</strong> sent an appointment reminder SMS to the customer
  <span class="activity-feed__date"><%= timestamp(sms_reminder_activity.created_at) %></span>
</li>

app/views/activities/_video_appointment_url_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= video_appointment_url_activity.id %>">
  <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
  <strong>The system</strong> sent the video appointment URL notification to the customer
  <span class="activity-feed__date"><%= timestamp(video_appointment_url_activity.created_at) %></span>
</li>

app/views/activities/_video_customer_exit_poll_activity.html.erb
<li class="activity-feed__item t-activity" id="activity-<%= video_customer_exit_poll_activity.id %>">
  <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
  <strong>The system</strong> sent a video appointment exit poll email
  <span class="activity-feed__date"><%= timestamp(video_customer_exit_poll_activity.created_at) %></span>
</li>